// <auto-generated />
using System;
using Discord.Bot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discord.Bot.Database.Migrations
{
    [DbContext(typeof(UserSayingsContext))]
    [Migration("20220625061242_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("Discord.Bot.Database.Models.Saying", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("IsmRecorder")
                        .HasColumnType("TEXT");

                    b.Property<string>("IsmSaying")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsmSaying")
                        .IsUnique();

                    b.HasIndex("Username");

                    b.ToTable("Sayings");
                });

            modelBuilder.Entity("Discord.Bot.Database.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Username");

                    b.HasIndex("GuildId", "Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Discord.Bot.Database.Models.Saying", b =>
                {
                    b.HasOne("Discord.Bot.Database.User", null)
                        .WithMany("Sayings")
                        .HasForeignKey("Username");
                });

            modelBuilder.Entity("Discord.Bot.Database.User", b =>
                {
                    b.Navigation("Sayings");
                });
#pragma warning restore 612, 618
        }
    }
}
